
name: Run Python Script with Selenium

on:
  #workflow_dispatch:
  #schedule:
    # Run the workflow every 6 hours
    - cron: "0 */6 * * *"

jobs:
  my_job:
    runs-on: ubuntu-latest
    timeout-minutes: 358  # Set timeout to 358 minutes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Remove existing ChromeDriver
      run: |
        sudo rm -f /usr/local/bin/chromedriver
        
    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chromedriver-linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run script
      env:
        DISPLAY: :99
      run: |
        sudo Xvfb :99 -ac &
        python script.py
